collections:
  - name: awx.awx
  - name: ansible.utils
  - name: ansible.posix
  - name: community.general
  - name: infra.controller_configuration
    version: "==2.1.94"
  - name: automationiberia.casc_setup
    version: "==2.0.22"
